FROM cosmtrek/air

WORKDIR /app

COPY go.mod ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o main .

EXPOSE 8080

ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main
