version: "3"

volumes:
  local_postgres_aods: {}
  api_volume: {}
  pgadmin: {}

services:
  gateway:
    container_name: itafm_aods_gw_dev
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.mqtt
    volumes:
      - .:/usr/src/app/
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
