version: "3"

services:
  gateway:
    container_name: itafm_aods_gw_dev
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.mqtt
    volumes:
      - .:/usr/src/app/
    network_mode: host
