services:
  kafka:
    image: redpandadata/redpanda:v24.2.9
    container_name: itafm_kafka_prod
    restart: always
    ports:
      - "9099:9092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --check=false
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://localhost:9099
    volumes:
      - kafka_data_prod:/var/lib/redpanda/data

  java_broker:
    container_name: itafm_amq_kafka_broker_prod
    build:
      context: .
      dockerfile: java-broker/Dockerfile
    restart: always
    env_file:
      - ./.envs/.production/.mqtt
      - ./.envs/.production/.kafka
    depends_on:
      - kafka
    network_mode: host

  gateway:
    container_name: itafm_aods_gw_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ./.envs/.production/.postgres
      - ./.envs/.production/.mqtt
      - ./.envs/.production/.kafka
    depends_on:
      - kafka
      - java_broker
    volumes:
      - .:/usr/src/app/
    network_mode: host

  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          if [ "$$(date +'%H:%M')" = '17:00' ]; then
            docker restart gateway
          fi
          sleep 60
        done

volumes:
  kafka_data_prod:
