services:
  gateway:
    container_name: itafm_aods_gw_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ./.envs/.production/.postgres
      - ./.envs/.production/.mqtt
    volumes:
      - .:/usr/src/app/
    network_mode: host

  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          if [ "$$(date +'%H:%M')" = '17:00' ]; then
            docker restart gateway
          fi
          sleep 60
        done

#     networks:
#       - agos_dj_agos_server_network

# networks:
#   agos_dj_agos_server_network:
#     external: true
